package pugilist_steve.mod.annoying_villagersbychentu.init;

import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import pugilist_steve.mod.annoying_villagersbychentu.AnnoyingVillagersbychentuMod;
import pugilist_steve.mod.annoying_villagersbychentu.entity.*;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)

public class AnnoyingVillagersbychentuModEntities {
    public static final DeferredRegister<EntityType<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.ENTITIES, AnnoyingVillagersbychentuMod.MODID);

    private static <T extends Entity> RegistryObject<EntityType<T>> register(String registryname, EntityType.Builder<T> entityTypeBuilder) {
        return REGISTRY.register(registryname, () -> {
            return entityTypeBuilder.build(registryname);
        });
    }    public static final RegistryObject<EntityType<BishouEntity>> BISHOU = register("projectile_bishou", EntityType.Builder.of(BishouEntity::new, MobCategory.MISC).setCustomClientFactory(BishouEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));

    @SubscribeEvent
    public static void init(FMLCommonSetupEvent event) {
        event.enqueueWork(() -> {
            CunMinZhenChaBingEntity.init();
            CczdzEntity.init();
            LanCunQiEntity.init();
            LuCunQiEntity.init();
            HongCunQiEntity.init();
            ZiCunQiEntity.init();
            CunZhenFuLuEntity.init();
            HongCunQiFuLuEntity.init();
            LanCunQiFuLuEntity.init();
            ZiCunQiFuLuEntity.init();
            GraveEntity.init();
            Grave2Entity.init();
            JianbingguoziEntity.init();
            WanJia1Entity.init();
            SteveEntity.init();
            Steve2Entity.init();
            FennudeshidifuEntity.init();
            KeLiSiEntity.init();
            GeLeiGeEntity.init();
            MrcolderEntity.init();
            Mrcolder2Entity.init();
            EnchanterEntity.init();
            AlexEntity.init();
            AlexVillagerEntity.init();
            MrMudgeMonkeyEntity.init();
            DiJiherobrineEntity.init();
            DijiyinfenshenEntity.init();
            HerobrinefenshenEntity.init();
            Herobrine2Entity.init();
            Herobrine3Entity.init();
            AnyinghimfenshenEntity.init();
            Herobrine7Entity.init();
            HbGaoJiFenShenEntity.init();
            DarkHerobrineEntity.init();
            GaojiherobrineEntity.init();
            LianyingfenshengEntity.init();
            SherenherobrineEntity.init();
            YingChuiHerobrineEntity.init();
            BlueDemonEntity.init();
            NishidierjieEntity.init();
            LingZhiEntity.init();
            ShiTi303Entity.init();
            Shiti303fenshenEntity.init();
            ZaiEZhiWangEntity.init();
            Zaiezhiwang2Entity.init();
            HongyizombieEntity.init();
            BeiGanRanJianBingGuoZiEntity.init();
            BeiganrandekelisiEntity.init();
            BbqEntity.init();
            JiemoEntity.init();
            HeiyaoshitiekuileiEntity.init();
            LanmeikuileiEntity.init();
            HuoyantiekuileiEntity.init();
            HongkuileiEntity.init();
            HejinzhulinEntity.init();
            ZibaokuileiEntity.init();
            CowEntity.init();
            PigEntity.init();
            SteveDeadEntity.init();
            GravedeadEntity.init();
            AlexdeadEntity.init();
            MrcolderdeadEntity.init();
            Null1Entity.init();
            Null2Entity.init();
            Null3Entity.init();
            Null4Entity.init();
            Null6Entity.init();
            LvcunqifuluEntity.init();
            BbdEntity.init();
            MaEntity.init();
            DeathSherenHerobrineEntity.init();
            BTridentEntity.init();
        });
    }    public static final RegistryObject<EntityType<DiamondShieldEntity>> DIAMOND_SHIELD = register("projectile_diamond_shield", EntityType.Builder.of(DiamondShieldEntity::new, MobCategory.MISC).setCustomClientFactory(DiamondShieldEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));

    @SubscribeEvent
    public static void registerAttributes(EntityAttributeCreationEvent event) {
        event.put(CUN_MIN_ZHEN_CHA_BING.get(), CunMinZhenChaBingEntity.createAttributes().build());
        event.put(CCZDZ.get(), CczdzEntity.createAttributes().build());
        event.put(LAN_CUN_QI.get(), LanCunQiEntity.createAttributes().build());
        event.put(LU_CUN_QI.get(), LuCunQiEntity.createAttributes().build());
        event.put(HONG_CUN_QI.get(), HongCunQiEntity.createAttributes().build());
        event.put(ZI_CUN_QI.get(), ZiCunQiEntity.createAttributes().build());
        event.put(CUN_ZHEN_FU_LU.get(), CunZhenFuLuEntity.createAttributes().build());
        event.put(HONG_CUN_QI_FU_LU.get(), HongCunQiFuLuEntity.createAttributes().build());
        event.put(LAN_CUN_QI_FU_LU.get(), LanCunQiFuLuEntity.createAttributes().build());
        event.put(ZI_CUN_QI_FU_LU.get(), ZiCunQiFuLuEntity.createAttributes().build());
        event.put(GRAVE.get(), GraveEntity.createAttributes().build());
        event.put(GRAVE_2.get(), Grave2Entity.createAttributes().build());
        event.put(JIANBINGGUOZI.get(), JianbingguoziEntity.createAttributes().build());
        event.put(WAN_JIA_1.get(), WanJia1Entity.createAttributes().build());
        event.put(STEVE.get(), SteveEntity.createAttributes().build());
        event.put(STEVE_2.get(), Steve2Entity.createAttributes().build());
        event.put(FENNUDESHIDIFU.get(), FennudeshidifuEntity.createAttributes().build());
        event.put(KE_LI_SI.get(), KeLiSiEntity.createAttributes().build());
        event.put(GE_LEI_GE.get(), GeLeiGeEntity.createAttributes().build());
        event.put(MRCOLDER.get(), MrcolderEntity.createAttributes().build());
        event.put(MRCOLDER_2.get(), Mrcolder2Entity.createAttributes().build());
        event.put(ENCHANTER.get(), EnchanterEntity.createAttributes().build());
        event.put(ALEX.get(), AlexEntity.createAttributes().build());
        event.put(ALEX_VILLAGER.get(), AlexVillagerEntity.createAttributes().build());
        event.put(MR_MUDGE_MONKEY.get(), MrMudgeMonkeyEntity.createAttributes().build());
        event.put(DI_JIHEROBRINE.get(), DiJiherobrineEntity.createAttributes().build());
        event.put(DIJIYINFENSHEN.get(), DijiyinfenshenEntity.createAttributes().build());
        event.put(HEROBRINEFENSHEN.get(), HerobrinefenshenEntity.createAttributes().build());
        event.put(HEROBRINE_2.get(), Herobrine2Entity.createAttributes().build());
        event.put(HEROBRINE_3.get(), Herobrine3Entity.createAttributes().build());
        event.put(ANYINGHIMFENSHEN.get(), AnyinghimfenshenEntity.createAttributes().build());
        event.put(HEROBRINE_7.get(), Herobrine7Entity.createAttributes().build());
        event.put(HB_GAO_JI_FEN_SHEN.get(), HbGaoJiFenShenEntity.createAttributes().build());
        event.put(DARK_HEROBRINE.get(), DarkHerobrineEntity.createAttributes().build());
        event.put(GAOJIHEROBRINE.get(), GaojiherobrineEntity.createAttributes().build());
        event.put(LIANYINGFENSHENG.get(), LianyingfenshengEntity.createAttributes().build());
        event.put(SHERENHEROBRINE.get(), SherenherobrineEntity.createAttributes().build());
        event.put(YING_CHUI_HEROBRINE.get(), YingChuiHerobrineEntity.createAttributes().build());
        event.put(BLUE_DEMON.get(), BlueDemonEntity.createAttributes().build());
        event.put(NISHIDIERJIE.get(), NishidierjieEntity.createAttributes().build());
        event.put(LING_ZHI.get(), LingZhiEntity.createAttributes().build());
        event.put(SHI_TI_303.get(), ShiTi303Entity.createAttributes().build());
        event.put(SHITI_303FENSHEN.get(), Shiti303fenshenEntity.createAttributes().build());
        event.put(ZAI_E_ZHI_WANG.get(), ZaiEZhiWangEntity.createAttributes().build());
        event.put(ZAIEZHIWANG_2.get(), Zaiezhiwang2Entity.createAttributes().build());
        event.put(HONGYIZOMBIE.get(), HongyizombieEntity.createAttributes().build());
        event.put(BEI_GAN_RAN_JIAN_BING_GUO_ZI.get(), BeiGanRanJianBingGuoZiEntity.createAttributes().build());
        event.put(BEIGANRANDEKELISI.get(), BeiganrandekelisiEntity.createAttributes().build());
        event.put(BBQ.get(), BbqEntity.createAttributes().build());
        event.put(JIEMO.get(), JiemoEntity.createAttributes().build());
        event.put(HEIYAOSHITIEKUILEI.get(), HeiyaoshitiekuileiEntity.createAttributes().build());
        event.put(LANMEIKUILEI.get(), LanmeikuileiEntity.createAttributes().build());
        event.put(HUOYANTIEKUILEI.get(), HuoyantiekuileiEntity.createAttributes().build());
        event.put(HONGKUILEI.get(), HongkuileiEntity.createAttributes().build());
        event.put(HEJINZHULIN.get(), HejinzhulinEntity.createAttributes().build());
        event.put(ZIBAOKUILEI.get(), ZibaokuileiEntity.createAttributes().build());
        event.put(COW.get(), CowEntity.createAttributes().build());
        event.put(PIG.get(), PigEntity.createAttributes().build());
        event.put(STEVE_DEAD.get(), SteveDeadEntity.createAttributes().build());
        event.put(GRAVEDEAD.get(), GravedeadEntity.createAttributes().build());
        event.put(ALEXDEAD.get(), AlexdeadEntity.createAttributes().build());
        event.put(MRCOLDERDEAD.get(), MrcolderdeadEntity.createAttributes().build());
        event.put(NULL_1.get(), Null1Entity.createAttributes().build());
        event.put(NULL_2.get(), Null2Entity.createAttributes().build());
        event.put(NULL_3.get(), Null3Entity.createAttributes().build());
        event.put(NULL_4.get(), Null4Entity.createAttributes().build());
        event.put(NULL_6.get(), Null6Entity.createAttributes().build());
        event.put(LVCUNQIFULU.get(), LvcunqifuluEntity.createAttributes().build());
        event.put(BBD.get(), BbdEntity.createAttributes().build());
        event.put(LUEDUOZHEWANGDEMA.get(), MaEntity.createAttributes().build());
        event.put(DEATH_SHEREN_HEROBRINE.get(), DeathSherenHerobrineEntity.createAttributes().build());
        event.put(B_TRIDENT.get(), BTridentEntity.createAttributes().build());
    }    public static final RegistryObject<EntityType<ZzidanEntity>> ZZIDAN = register("projectile_zzidan", EntityType.Builder.of(ZzidanEntity::new, MobCategory.MISC).setCustomClientFactory(ZzidanEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<FumomoyingzhenzhuEntity>> FUMOMOYINGZHENZHU = register("projectile_fumomoyingzhenzhu", EntityType.Builder.of(FumomoyingzhenzhuEntity::new, MobCategory.MISC).setCustomClientFactory(FumomoyingzhenzhuEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<HeisezhenzhuEntity>> HEISEZHENZHU = register("projectile_heisezhenzhu", EntityType.Builder.of(HeisezhenzhuEntity::new, MobCategory.MISC).setCustomClientFactory(HeisezhenzhuEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<FaguangdezhenzhuEntity>> FAGUANGDEZHENZHU = register("projectile_faguangdezhenzhu", EntityType.Builder.of(FaguangdezhenzhuEntity::new, MobCategory.MISC).setCustomClientFactory(FaguangdezhenzhuEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<CunMinZhenChaBingEntity>> CUN_MIN_ZHEN_CHA_BING = register("cun_min_zhen_cha_bing", EntityType.Builder.of(CunMinZhenChaBingEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(CunMinZhenChaBingEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<CczdzEntity>> CCZDZ = register("cczdz", EntityType.Builder.of(CczdzEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(CczdzEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<LanCunQiEntity>> LAN_CUN_QI = register("lan_cun_qi", EntityType.Builder.of(LanCunQiEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(LanCunQiEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<LuCunQiEntity>> LU_CUN_QI = register("lu_cun_qi", EntityType.Builder.of(LuCunQiEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(LuCunQiEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<HongCunQiEntity>> HONG_CUN_QI = register("hong_cun_qi", EntityType.Builder.of(HongCunQiEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(HongCunQiEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<ZiCunQiEntity>> ZI_CUN_QI = register("zi_cun_qi", EntityType.Builder.of(ZiCunQiEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(ZiCunQiEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<CunZhenFuLuEntity>> CUN_ZHEN_FU_LU = register("cun_zhen_fu_lu", EntityType.Builder.of(CunZhenFuLuEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(CunZhenFuLuEntity::new).sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<HongCunQiFuLuEntity>> HONG_CUN_QI_FU_LU = register("hong_cun_qi_fu_lu", EntityType.Builder.of(HongCunQiFuLuEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(HongCunQiFuLuEntity::new).sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<LanCunQiFuLuEntity>> LAN_CUN_QI_FU_LU = register("lan_cun_qi_fu_lu", EntityType.Builder.of(LanCunQiFuLuEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(LanCunQiFuLuEntity::new).sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<ZiCunQiFuLuEntity>> ZI_CUN_QI_FU_LU = register("zi_cun_qi_fu_lu", EntityType.Builder.of(ZiCunQiFuLuEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(ZiCunQiFuLuEntity::new).sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<GraveEntity>> GRAVE = register("grave", EntityType.Builder.of(GraveEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(GraveEntity::new).fireImmune().sized(0.5f, 1.8f));
    public static final RegistryObject<EntityType<Grave2Entity>> GRAVE_2 = register("grave_2", EntityType.Builder.of(Grave2Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(380).setUpdateInterval(3).setCustomClientFactory(Grave2Entity::new).fireImmune().sized(0.5f, 1.8f));
    public static final RegistryObject<EntityType<JianbingguoziEntity>> JIANBINGGUOZI = register("jianbingguozi", EntityType.Builder.of(JianbingguoziEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(JianbingguoziEntity::new).sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<WanJia1Entity>> WAN_JIA_1 = register("wan_jia_1", EntityType.Builder.of(WanJia1Entity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(WanJia1Entity::new).sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<SteveEntity>> STEVE = register("steve", EntityType.Builder.of(SteveEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(SteveEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Steve2Entity>> STEVE_2 = register("steve_2", EntityType.Builder.of(Steve2Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(Steve2Entity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<FennudeshidifuEntity>> FENNUDESHIDIFU = register("fennudeshidifu", EntityType.Builder.of(FennudeshidifuEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(FennudeshidifuEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<KeLiSiEntity>> KE_LI_SI = register("ke_li_si", EntityType.Builder.of(KeLiSiEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(KeLiSiEntity::new).sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<GeLeiGeEntity>> GE_LEI_GE = register("ge_lei_ge", EntityType.Builder.of(GeLeiGeEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(GeLeiGeEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<MrcolderEntity>> MRCOLDER = register("mrcolder", EntityType.Builder.of(MrcolderEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MrcolderEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Mrcolder2Entity>> MRCOLDER_2 = register("mrcolder_2", EntityType.Builder.of(Mrcolder2Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(Mrcolder2Entity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<EnchanterEntity>> ENCHANTER = register("enchanter", EntityType.Builder.of(EnchanterEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(EnchanterEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<AlexEntity>> ALEX = register("alex", EntityType.Builder.of(AlexEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(AlexEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<AlexVillagerEntity>> ALEX_VILLAGER = register("alex_villager", EntityType.Builder.of(AlexVillagerEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(AlexVillagerEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<MrMudgeMonkeyEntity>> MR_MUDGE_MONKEY = register("mr_mudge_monkey", EntityType.Builder.of(MrMudgeMonkeyEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(MrMudgeMonkeyEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<DiJiherobrineEntity>> DI_JIHEROBRINE = register("di_jiherobrine", EntityType.Builder.of(DiJiherobrineEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(DiJiherobrineEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<DijiyinfenshenEntity>> DIJIYINFENSHEN = register("dijiyinfenshen", EntityType.Builder.of(DijiyinfenshenEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(DijiyinfenshenEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<HerobrinefenshenEntity>> HEROBRINEFENSHEN = register("herobrinefenshen", EntityType.Builder.of(HerobrinefenshenEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(HerobrinefenshenEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Herobrine2Entity>> HEROBRINE_2 = register("herobrine_2", EntityType.Builder.of(Herobrine2Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(Herobrine2Entity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Herobrine3Entity>> HEROBRINE_3 = register("herobrine_3", EntityType.Builder.of(Herobrine3Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(Herobrine3Entity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<AnyinghimfenshenEntity>> ANYINGHIMFENSHEN = register("anyinghimfenshen", EntityType.Builder.of(AnyinghimfenshenEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(AnyinghimfenshenEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Herobrine7Entity>> HEROBRINE_7 = register("herobrine_7", EntityType.Builder.of(Herobrine7Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(Herobrine7Entity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<HbGaoJiFenShenEntity>> HB_GAO_JI_FEN_SHEN = register("hb_gao_ji_fen_shen", EntityType.Builder.of(HbGaoJiFenShenEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(HbGaoJiFenShenEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<DarkHerobrineEntity>> DARK_HEROBRINE = register("dark_herobrine", EntityType.Builder.of(DarkHerobrineEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(DarkHerobrineEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<GaojiherobrineEntity>> GAOJIHEROBRINE = register("gaojiherobrine", EntityType.Builder.of(GaojiherobrineEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(GaojiherobrineEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<LianyingfenshengEntity>> LIANYINGFENSHENG = register("lianyingfensheng", EntityType.Builder.of(LianyingfenshengEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(LianyingfenshengEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<SherenherobrineEntity>> SHERENHEROBRINE = register("sherenherobrine", EntityType.Builder.of(SherenherobrineEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(SherenherobrineEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<YingChuiHerobrineEntity>> YING_CHUI_HEROBRINE = register("ying_chui_herobrine", EntityType.Builder.of(YingChuiHerobrineEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(YingChuiHerobrineEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<BlueDemonEntity>> BLUE_DEMON = register("blue_demon", EntityType.Builder.of(BlueDemonEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(BlueDemonEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<NishidierjieEntity>> NISHIDIERJIE = register("nishidierjie", EntityType.Builder.of(NishidierjieEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(NishidierjieEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<LingZhiEntity>> LING_ZHI = register("ling_zhi", EntityType.Builder.of(LingZhiEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(LingZhiEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<ShiTi303Entity>> SHI_TI_303 = register("shi_ti_303", EntityType.Builder.of(ShiTi303Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(ShiTi303Entity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Shiti303fenshenEntity>> SHITI_303FENSHEN = register("shiti_303fenshen", EntityType.Builder.of(Shiti303fenshenEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(Shiti303fenshenEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<ZaiEZhiWangEntity>> ZAI_E_ZHI_WANG = register("zai_e_zhi_wang", EntityType.Builder.of(ZaiEZhiWangEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(ZaiEZhiWangEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Zaiezhiwang2Entity>> ZAIEZHIWANG_2 = register("zaiezhiwang_2", EntityType.Builder.of(Zaiezhiwang2Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(Zaiezhiwang2Entity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<HongyizombieEntity>> HONGYIZOMBIE = register("hongyizombie", EntityType.Builder.of(HongyizombieEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(HongyizombieEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<BeiGanRanJianBingGuoZiEntity>> BEI_GAN_RAN_JIAN_BING_GUO_ZI = register("bei_gan_ran_jian_bing_guo_zi", EntityType.Builder.of(BeiGanRanJianBingGuoZiEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(BeiGanRanJianBingGuoZiEntity::new).sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<BeiganrandekelisiEntity>> BEIGANRANDEKELISI = register("beiganrandekelisi", EntityType.Builder.of(BeiganrandekelisiEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(BeiganrandekelisiEntity::new).sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<BbqEntity>> BBQ = register("bbq", EntityType.Builder.of(BbqEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(BbqEntity::new).fireImmune().sized(0.4f, 0.7f));
    public static final RegistryObject<EntityType<JiemoEntity>> JIEMO = register("jiemo", EntityType.Builder.of(JiemoEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(JiemoEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<HeiyaoshitiekuileiEntity>> HEIYAOSHITIEKUILEI = register("heiyaoshitiekuilei", EntityType.Builder.of(HeiyaoshitiekuileiEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(HeiyaoshitiekuileiEntity::new).fireImmune().sized(0.6f, 2.8f));
    public static final RegistryObject<EntityType<LanmeikuileiEntity>> LANMEIKUILEI = register("lanmeikuilei", EntityType.Builder.of(LanmeikuileiEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(LanmeikuileiEntity::new).fireImmune().sized(0.6f, 2.8f));
    public static final RegistryObject<EntityType<HuoyantiekuileiEntity>> HUOYANTIEKUILEI = register("huoyantiekuilei", EntityType.Builder.of(HuoyantiekuileiEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(HuoyantiekuileiEntity::new).fireImmune().sized(0.6f, 2.8f));
    public static final RegistryObject<EntityType<HongkuileiEntity>> HONGKUILEI = register("hongkuilei", EntityType.Builder.of(HongkuileiEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(HongkuileiEntity::new).fireImmune().sized(0.6f, 2.8f));
    public static final RegistryObject<EntityType<HejinzhulinEntity>> HEJINZHULIN = register("hejinzhulin", EntityType.Builder.of(HejinzhulinEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(HejinzhulinEntity::new).fireImmune().sized(0.6f, 1.95f));
    public static final RegistryObject<EntityType<ZibaokuileiEntity>> ZIBAOKUILEI = register("zibaokuilei", EntityType.Builder.of(ZibaokuileiEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(ZibaokuileiEntity::new).fireImmune().sized(0.6f, 2.8f));
    public static final RegistryObject<EntityType<CowEntity>> COW = register("cow", EntityType.Builder.of(CowEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(CowEntity::new).sized(0.9f, 1.4f));
    public static final RegistryObject<EntityType<PigEntity>> PIG = register("pig", EntityType.Builder.of(PigEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(PigEntity::new).sized(0.9f, 0.9f));
    public static final RegistryObject<EntityType<SteveDeadEntity>> STEVE_DEAD = register("steve_dead", EntityType.Builder.of(SteveDeadEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(SteveDeadEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<GravedeadEntity>> GRAVEDEAD = register("gravedead", EntityType.Builder.of(GravedeadEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(GravedeadEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<AlexdeadEntity>> ALEXDEAD = register("alexdead", EntityType.Builder.of(AlexdeadEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(AlexdeadEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<MrcolderdeadEntity>> MRCOLDERDEAD = register("mrcolderdead", EntityType.Builder.of(MrcolderdeadEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(MrcolderdeadEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Null1Entity>> NULL_1 = register("null_1", EntityType.Builder.of(Null1Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(Null1Entity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Null2Entity>> NULL_2 = register("null_2", EntityType.Builder.of(Null2Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(Null2Entity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Null3Entity>> NULL_3 = register("null_3", EntityType.Builder.of(Null3Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(Null3Entity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Null4Entity>> NULL_4 = register("null_4", EntityType.Builder.of(Null4Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(Null4Entity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<Null6Entity>> NULL_6 = register("null_6", EntityType.Builder.of(Null6Entity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(Null6Entity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<LvcunqifuluEntity>> LVCUNQIFULU = register("lvcunqifulu", EntityType.Builder.of(LvcunqifuluEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(LvcunqifuluEntity::new).sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<BbdEntity>> BBD = register("bbd", EntityType.Builder.of(BbdEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(BbdEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<MaEntity>> LUEDUOZHEWANGDEMA = register("lueduozhewangdema", EntityType.Builder.of(MaEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(128).setUpdateInterval(3).setCustomClientFactory(MaEntity::new).fireImmune().sized(0.4f, 0.7f));
    public static final RegistryObject<EntityType<FulubuhuoqiEntity>> FULUBUHUOQI = register("projectile_fulubuhuoqi", EntityType.Builder.of(FulubuhuoqiEntity::new, MobCategory.MISC).setCustomClientFactory(FulubuhuoqiEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<BluedemontridentEntity>> BLUEDEMONTRIDENT = register("projectile_bluedemontrident", EntityType.Builder.of(BluedemontridentEntity::new, MobCategory.MISC).setCustomClientFactory(BluedemontridentEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<YinshenEntity>> YINSHEN = register("projectile_yinshen", EntityType.Builder.of(YinshenEntity::new, MobCategory.MISC).setCustomClientFactory(YinshenEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<HerobrinejiyanEntity>> HEROBRINEJIYAN = register("projectile_herobrinejiyan", EntityType.Builder.of(HerobrinejiyanEntity::new, MobCategory.MISC).setCustomClientFactory(HerobrinejiyanEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<BaozhabishouEntity>> BAOZHABISHOU = register("projectile_baozhabishou", EntityType.Builder.of(BaozhabishouEntity::new, MobCategory.MISC).setCustomClientFactory(BaozhabishouEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<ZhizhuwangEntity>> ZHIZHUWANG = register("projectile_zhizhuwang", EntityType.Builder.of(ZhizhuwangEntity::new, MobCategory.MISC).setCustomClientFactory(ZhizhuwangEntity::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));
    public static final RegistryObject<EntityType<DeathSherenHerobrineEntity>> DEATH_SHEREN_HEROBRINE = register("death_sheren_herobrine", EntityType.Builder.of(DeathSherenHerobrineEntity::new, MobCategory.CREATURE).setShouldReceiveVelocityUpdates(true).setTrackingRange(256).setUpdateInterval(3).setCustomClientFactory(DeathSherenHerobrineEntity::new).fireImmune().sized(0.6f, 1.8f));
    public static final RegistryObject<EntityType<BTridentEntity>> B_TRIDENT = register("b_trident", EntityType.Builder.of(BTridentEntity::new, MobCategory.MONSTER).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(3).setCustomClientFactory(BTridentEntity::new).fireImmune().sized(0.6f, 1.8f));






}
